# Generated by Django 4.2.7 on 2023-11-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_rename_message_room_chat_chat_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
